Repository portamor/curso, pull requests merged in 2023-04, with the labels that each got.

#56 asocioacion de videos y sections
  Backend-P/src/services/videoService.js
Labels: bug

#63 Pagina - Clase
  Backend-P/src/controllers/coursesController.js
  Backend-P/src/controllers/usersController.js
  Backend-P/src/controllers/videosController.js
  Backend-P/src/models/Courses.js
  Backend-P/src/routes/coursesRouter.js
  Backend-P/src/routes/usersRouter.js
  Backend-P/src/routes/videosRouter.js
  Backend-P/src/services/userService.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/ClassDetail/ClassDetail.jsx
  client/src/Components/ClassDetail/ClassDetail.module.css
  client/src/Components/CourseAccordion/CourseAccordion.jsx
  client/src/Components/CourseAccordion/CourseAccordion.module.css
  client/src/Components/CustomButton/CustomButton.jsx
  client/src/Components/InstructorDetail/InstructorDetail.jsx
  client/src/Components/InstructorDetail/InstructorDetail.module.css
  client/src/Components/ReviewCard/ReviewCard.jsx
  client/src/Components/ReviewCard/ReviewCard.module.css
  client/src/Components/SelectedData/SelectedData.jsx
  client/src/Components/SelectedData/SelectedData.module.css
  client/src/Components/UserCard/UserCard.jsx
  client/src/Components/UserCard/UserCard.module.css
  client/src/Redux/actions.js
  client/src/Redux/reducer.js
  client/src/constants/index.js
  client/src/images/certified-portamor.svg
  client/src/images/fondo-img.svg
  client/src/images/reviews-icon.svg
  client/src/images/users-icon.svg
  client/src/images/ver-video.svg
  client/src/images/youtube-icon.svg
  client/src/utils/index.js
Labels: enhancement

#69 Creacion de comentario
  client/src/Components/ClassDetail/ClassDetail.jsx
  client/src/Components/CourseAccordion/CourseAccordion.jsx
  client/src/Components/CreateReview/CreateReview.module.css
  client/src/Components/CustomButton/CustomButton.jsx
  client/src/Components/SelectedData/SelectedData.jsx
  client/src/Redux/actions.js
  client/src/Redux/reducer.js
  client/src/constants/actionsContants/index.js
  client/src/constants/classDetailConstants/index.js
  client/src/constants/createReviewConstants/index.js
  client/src/constants/index.js
  client/src/index.js
  client/src/utils/index.js
Labels: duplicate

#112 botones ternarios de inscripcion, ver clases e inicio de sesion
  client/src/Components/CourseDetail/CourseDetail.jsx
  client/src/Components/CourseDetail/CourseDetail.module.css
  client/src/Components/CourseDetail/GeneralVision/GeneralVision.jsx
  client/src/Components/CourseDetail/GeneralVision/GeneralVision.module.css
  client/src/Components/FormInsciption/FormInscription.jsx
  client/src/Components/Login/Login.jsx
  client/src/Components/ModalInscription/ModalInscription.jsx
  client/src/Components/ModalInscription/ModalInscription.module.css
  client/src/Components/NavBar/NavBar.jsx
Labels: enhancement

#113 Re diseño y Footer
  Backend-P/index.js
  Backend-P/src/models/Courses.js
  Backend-P/src/services/courseService.js
  client/src/App.js
  client/src/Components/ClassDetail/ClassDetail.jsx
  client/src/Components/ClassDetail/ClassDetail.module.css
  client/src/Components/CourseCard/CourseCard.jsx
  client/src/Components/CourseCard/CourseCard.module.css
  client/src/Components/CourseDetail/CourseDetail.jsx
  client/src/Components/CourseDetail/CourseDetail.module.css
  client/src/Components/CourseDetail/FYQ/FYQ.jsx
  client/src/Components/CourseDetail/FYQ/FYQ.module.css
  client/src/Components/CourseDetail/FYQAccordion/FYQ.module.css
  client/src/Components/CourseDetail/FYQAccordion/FYQAccordion.jsx
  client/src/Components/CourseDetail/GeneralVision/GeneralVision.jsx
  client/src/Components/CourseDetail/GeneralVision/GeneralVision.module.css
  client/src/Components/CourseDetail/SelectedContent/SelectedContent.jsx
  client/src/Components/CourseDetail/SelectedContent/SelectedContent.module.css
  client/src/Components/CustomButton/CustomButton.module.css
  client/src/Components/Footer/Footer.jsx
  client/src/Components/Footer/Footer.module.css
  client/src/Components/ModalInscription/ModalInscription.jsx
  client/src/Components/ModalInscription/ModalInscription.module.css
  client/src/Components/Paginated/Paginated.jsx
  client/src/Components/Paginated/Paginated.module.css
  client/src/Components/SelectedData/SelectedData.jsx
  client/src/Components/SelectedData/SelectedData.module.css
  client/src/Redux/reducer.js
  client/src/images/LogoRed.svg
  client/src/index.css
Labels: bug, enhancement

#121 Se crearon las opciones para Editar curso, eliminar curso
  client/src/Components/CourseCard/CourseCard.jsx
  client/src/Components/CourseDetail/GeneralVision/GeneralVision.jsx
  client/src/Components/Forms/CreateCourse/FormCourse.jsx
  client/src/Components/Forms/CreateInstructor/CreateInstructor.jsx
  client/src/Components/NavBar/NavBar.jsx
  client/src/Redux/actions.js
  client/src/constants/actionsContants/index.js
Labels: enhancement
